[package]
name = "rustware"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
float-cmp = "0.9.0"
crossbeam = "0.8.2"
multiqueue2 = "0.1.7"
strum = "0.24.1"
strum_macros = "0.24.1"
