backend {
     ssl_vision_ip: "224.5.23.2"
     ssl_vision_port: 10020
     gamecontroller_ip: "224.5.23.1"
     gamecontroller_port: 10003
}
perception {
    team_name: "Underbots"
    defending_side: NEGATIVE
    friendly_color: BLUE
}
gameplay {
    div_a: false
}
gui_bridge {
    unix_socket_prefix: "ipc:///tmp/underbots_zmq_"
    ssl_vision_topic: "ssl_vision"
    ssl_gc_topic: "ssl_gc"
    log_topic: "log"
    world_topic: "world"
    metrics_topic: "metrics"
}
rules {
    robot_max_radius: 0.09
    ball_max_radius: 0.0215
    max_robot_id: 15
    max_kick_speed: 6.5
    div_a_total_field_x_length: 13.4
    div_a_total_field_y_length: 10.4
    div_b_total_field_x_length: 10.4
    div_b_total_field_y_length: 7.4
    ball_in_play_after_restart_move_dist: 0.05
}
